### ISSUE TITLE
Website?

### ISSUE THREAD

**Issue by TrickJoker312** [nekumelon/TamGames#1]
So... what's the site?

**Comment by nekumelon** [comment]
[tamgames](https://tamgames.net)

**Comment by TrickJoker312** [comment]
Site can't be reached....

**Comment by nekumelon** [comment]
Are you sure? the url is:
https://tamgames.net
It is up and running.

**Comment by TrickJoker312** [comment]
Never mind, it works now! Thank you for your help!
