### ISSUE TITLE
Game takedown request from 3kh0

### ISSUE THREAD

**Issue by airtag8892** [nekumelon/TamGames#2]
Hey! This is airtag#8892 from 3kh0, I am a moderator in the Discord server.

I see that you made "https://tamgames.net/", this has a game taken from 3kh0's game site. The game taken was https://tamgames.net/#/paperIO, 

Please take down the game. You can contact us at discord.gg/3kh0, and tell me your username, I'll be happy to add you into the ticket.

If you don't trust me, you can verify my role in 3kh0 by joining the official Discord server and looking for me. If you don't trust the link I listed above, go to https://3kh0.github.io/ and open the Discord widget, then "Open Discord App".

Attached below is a screenshot of the stolen game.
![image](https://user-images.githubusercontent.com/120539605/221071040-46a64d9e-e329-4fcc-854a-d9c40f2d5640.png)

**Comment by Asleep123** [comment]
I can backup, it’s not fun to deal with 3kh0. (no hate <3)

**Comment by nekumelon** [comment]
I am sorry for the late response to your request, I have been on a trip and unable to look at my emails/GitHub. I don't currently have access to my computer until Monday, however I will look into giving proper credit for the game once I do. Thanks for understanding!

**Comment by airtag8892** [comment]
Alright, sounds good. I was worried because this is supposed to be a takedown request but Echo said it was fine to just give credit.

**Comment by nekumelon** [comment]
No worries, I will gladly add credit!

**Comment by Asleep123** [comment]
> I am sorry for the late response to your request, I have been on a trip and unable to look at my emails/GitHub. I don't currently have access to my computer until Monday, however I will look into giving proper credit for the game once I do. Thanks for understanding!

Sounds like a bit of a lie…
You changed part of the game to say it was made by tamgames, and that was yesterday.
I don’t mind if you lied or not, but just a little bit of information.

**Comment by nekumelon** [comment]
Just a clarification, I didn't have access to my email or GitHub account, as I was not on my desktop. I was able to write code changes from my secondary computer, which I brought with me. I have no intention of stealing credit for games, I clearly state that I did not make any of the games, nor am I taking credit for them, on the information page. Yes, I did change the text of the game, not to take credit, but to clean up the games for the website. I don't mean any harm, and I will add proper credit once I have the chance.

**Comment by airtag8892** [comment]
> Just a clarification, I didn't have access to my email or GitHub account, as I was not on my desktop. I was able to write code changes from my secondary computer, which I brought with me. I have no intention of stealing credit for games, I clearly state that I did not make any of the games, nor am I taking credit for them, on the information page. Yes, I did change the text of the game, not to take credit, but to clean up the games for the website. I don't mean any harm, and I will add proper credit once I have the chance.

Alright, I'm going to give you a little extra time. You have 120 hours to either give credit or remove the game from the site before we file a DMCA.

But if you have a secondary computer, why don't you use that to give credit/remove the game?

**Comment by nekumelon** [comment]
I'm currently at an event where I was unable to bring my laptop (different from the one I was at when the request was opened). I'll have my computer by Monday, and will add the required credit.

**Comment by Asleep123** [comment]
not sure if i believe this but ok

**Comment by nekumelon** [comment]
I have added the text "Paper.IO, brought to you by 3kh0.github.io!" to the Paper.IO game screen. If further credit is required, please reopen the issue. Thanks for understanding!
